"""Add image_url to community_posts

Revision ID: 102ed59fd221
Revises: 68fbbeffeafa
Create Date: 2026-07-13 19:33:02.037364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102ed59fd221'
down_revision = '68fbbeffeafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
